#!/bin/sh -e

# XXX with or without etc and var already in place
# XXX without a pkg symlink, packages go to wrong place pkgsrc/packages
# XXX can't yet build other packages simultaneously from another shell
# XXX something pulls in tex and X stuff?

_VINTAGE=`date '+%Y%m%d'`
_PHILO=$HOME/philo
PKGSRCDIR=${_PHILO}/pkgsrc-current

philo_software_reinstall_bootstrap() {
	cd $PKGSRCDIR/bootstrap
	env SH=/bin/bash ./bootstrap				\
		--unprivileged					\
		--prefix ${_PHILO}/.pkg-${_VINTAGE}		\
		--pkgdbdir ${_PHILO}/.pkg-${_VINTAGE}/.pkgdb	\
		--varbase ${_PHILO}/var				\
		--sysconfdir ${_PHILO}/etc			\
		--prefer-pkgsrc yes				\
		--abi 64
#--mk-fragment ${_PHILO}/mk.conf
#--gzip-binary-kit XXX
	./cleanup
}

philo_software_reinstall_build() {
	PATH=`echo $PATH | sed -e "s|/pkg/|/.pkg-${_VINTAGE}/|g"`
	cd ${_PHILO}/etc
	# nope it's a readlink now
	sed -e "s|^\(_VINTAGE=.*\)[0-9]\{8,\}|\1${_VINTAGE}|"	\
		< mk.conf > mk.conf.new				\
		&& mv mk.conf.new mk.conf

	PHILO_PACKAGES='checkperms shlock tmux ikiwiki p5-Text-Markdown graphviz keychain mp3splt normalize'
	for i in $PHILO_PACKAGES; do
		cd $PKGSRCDIR/*/$i
		bmake package-install clean || echo >&2 "XXX Philo: $i"
	done
}

philo_software_reinstall_bless() {
	cd ${_PHILO} && rm pkg && ln -s .pkg-${_VINTAGE} pkg
}

philo_software_reinstall_print_start() {
	STARTTIME=`date`
	echo >&2 "Starting Philo software reinstall"
	echo >&2
}

philo_software_reinstall_print_finish() {
	FINISHTIME=`date`
	echo >&2 "Completed Philo software reinstall!"
	echo >&2 "Started:  $STARTTIME"
	echo >&2 "Finished: $FINISHTIME"
	echo >&2
}

main() {
	philo_software_reinstall_print_start
	philo_software_reinstall_bootstrap
	philo_software_reinstall_build
	philo_software_reinstall_bless
	philo_software_reinstall_print_finish
}

main "$@"
exit $?
